### ISSUE TITLE
The build fails with 'filesystem' file not found error

### ISSUE THREAD

**Issue by wangyaopw** [world-federation-of-advertisers/common-cpp#28]
I am building the code inside the docker container (running the wfameasurement/bazel image) on my Macbook. And it fails with

```
src/main/cc/common_cpp/protobuf_util/textproto_io.cc:22:10: fatal error: 'filesystem' file not found
#include <filesystem>
```

I'm wondering how it passed the github action check.

**Comment by SanjayVas** [comment]
Is this using the extra config options specified in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/container.bazelrc ? Those are needed to ensure that the correct C++ toolchain is used.

**Comment by wangyaopw** [comment]
> I believe the issue is that our container image has too old a version of libstdc++. From https://en.cppreference.com/w/cpp/filesystem:
> 
> > Using this library may require additional compiler/linker options. GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs.
> 
> The simplest solution is to upgrade our build container image to be based on Ubuntu 20.04 (focal) instead of 18.04 (bionic). The GHA runner likely has a newer libstdc++ installed.

That sounds good. Do you want to have a try? Hope the upgrade won't break anything else.

**Comment by wangyaopw** [comment]
Thank you Sanjay!
